# Generated by Django 4.2 on 2023-04-04 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamsapp', '0004_album_alter_playlist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('length', models.DurationField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jamsapp.album')),
            ],
        ),
    ]
