# Generated by Django 4.2 on 2023-04-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamsapp', '0007_album_genres_alter_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='songs',
            field=models.ManyToManyField(related_name='artists', related_query_name='artist', to='jamsapp.song'),
        ),
    ]
