# Generated by Django 4.2 on 2023-04-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamsapp', '0008_artist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(related_name='playlists', related_query_name='playlist', to='jamsapp.song'),
        ),
    ]
