# Generated by Django 4.2 on 2023-04-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamsapp', '0009_playlist_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='songs',
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(related_name='songs', related_query_name='song', to='jamsapp.artist'),
        ),
    ]
